###
POST http://localhost:4000/login
Content-Type: application/json

{
  "correo":"Luis@gmail.com",
  "contrasenia":"12345678"
}

###
GET  http://localhost:4000/listDepartment
Content-Type: application/json
Authorization: Barrer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0MjQyIiwibmFtZSI6Ikplc3NpY2EgVGVtcG9yYWwiLCJuaWNrbmFtZSI6Ikplc3MifQ.ztIhsiqvnDBkBgKQXN09NI-tiQ4ePv5SbSgSL-f_aDo



###
POST  http://localhost:4000/departmentById
Content-Type: application/json
Authorization: Barrer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhQkQiOnsibm9tYnJlIjoiTHVpcyIsImNvcnJlbyI6Ikx1aXNAZ21haWwuY29tIiwiZG9ibGVBdXRoIjp0cnVlLCJlc3RhZG8iOnRydWV9LCJpYXQiOjE2MzY3NzcyMjQsImV4cCI6MTYzNjgxMzIyNH0.iQFs4Nzj1s7AfHcNDbb3MTTMuRd_6YkwqBaE9Bl1p94

{
  "id": 7
}

###
POST http://localhost:4000/deleteDepartment
Content-Type: application/json
Authorization: Barrer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhQkQiOnsibm9tYnJlIjoiTHVpcyIsImNvcnJlbyI6Ikx1aXNAZ21haWwuY29tIiwiZG9ibGVBdXRoIjp0cnVlLCJlc3RhZG8iOnRydWV9LCJpYXQiOjE2MzY3NzcyMjQsImV4cCI6MTYzNjgxMzIyNH0.iQFs4Nzj1s7AfHcNDbb3MTTMuRd_6YkwqBaE9Bl1p94

{
  "id": 7
}

###
POST http://localhost:4000/department
Content-Type: application/json
Authorization: Barrer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhQkQiOnsibm9tYnJlIjoiTHVpcyIsImNvcnJlbyI6Ikx1aXNAZ21haWwuY29tIiwiZG9ibGVBdXRoIjp0cnVlLCJlc3RhZG8iOnRydWV9LCJpYXQiOjE2MzY3NzcyMjQsImV4cCI6MTYzNjgxMzIyNH0.iQFs4Nzj1s7AfHcNDbb3MTTMuRd_6YkwqBaE9Bl1p94

{
  "descripcion": "Ventas"
}


###
PUT http://localhost:4000/department
Content-Type: application/json
Authorization: Barrer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhQkQiOnsibm9tYnJlIjoiTHVpcyIsImNvcnJlbyI6Ikx1aXNAZ21haWwuY29tIiwiZG9ibGVBdXRoIjp0cnVlLCJlc3RhZG8iOnRydWV9LCJpYXQiOjE2MzY3NzcyMjQsImV4cCI6MTYzNjgxMzIyNH0.iQFs4Nzj1s7AfHcNDbb3MTTMuRd_6YkwqBaE9Bl1p94

{
  "id": 7,
  "descripcion": "Ventas"
}